<?php

namespace Laratrade\Trader\Facades;

use Illuminate\Support\Facades\Facade;
use Laratrade\Trader\Contracts\Trader as TraderContract;

/**
 * Class Trader
 * @package Laratrade\Trader\Facades
 *
 * @method static acos()
 * @method static ad()
 * @method static add()
 * @method static adosc()
 * @method static adx()
 * @method static adxr()
 * @method static apo()
 * @method static aroon()
 * @method static aroonosc()
 * @method static asin()
 * @method static atan()
 * @method static atr()
 * @method static avgprice()
 * @method static bbands()
 * @method static beta()
 * @method static bop()
 * @method static cci()
 * @method static cdl2crows()
 * @method static cdl3blackcrows()
 * @method static cdl3inside()
 * @method static cdl3linestrike()
 * @method static cdl3outside()
 * @method static cdl3starsinsouth()
 * @method static cdl3whitesoldiers()
 * @method static cdlabandonedbaby()
 * @method static cdladvanceblock()
 * @method static cdlbelthold()
 * @method static cdlbreakaway()
 * @method static cdlclosingmarubozu()
 * @method static cdlconcealbabyswall()
 * @method static cdlcounterattack()
 * @method static cdldarkcloudcover()
 * @method static cdldoji()
 * @method static cdldojistar()
 * @method static cdldragonflydoji()
 * @method static cdlengulfing()
 * @method static cdleveningdojistar()
 * @method static cdleveningstar()
 * @method static cdlgapsidesidewhite()
 * @method static cdlgravestonedoji()
 * @method static cdlhammer()
 * @method static cdlhangingman()
 * @method static cdlharami()
 * @method static cdlharamicross()
 * @method static cdlhighwave()
 * @method static cdlhikkake()
 * @method static cdlhikkakemod()
 * @method static cdlhomingpigeon()
 * @method static cdlidentical3crows()
 * @method static cdlinneck()
 * @method static cdlinvertedhammer()
 * @method static cdlkicking()
 * @method static cdlkickingbylength()
 * @method static cdlladderbottom()
 * @method static cdllongleggeddoji()
 * @method static cdllongline()
 * @method static cdlmarubozu()
 * @method static cdlmatchinglow()
 * @method static cdlmathold()
 * @method static cdlmorningdojistar()
 * @method static cdlmorningstar()
 * @method static cdlonneck()
 * @method static cdlpiercing()
 * @method static cdlrickshawman()
 * @method static cdlrisefall3methods()
 * @method static cdlseparatinglines()
 * @method static cdlshootingstar()
 * @method static cdlshortline()
 * @method static cdlspinningtop()
 * @method static cdlstalledpattern()
 * @method static cdlsticksandwich()
 * @method static cdltakuri()
 * @method static cdltasukigap()
 * @method static cdlthrusting()
 * @method static cdltristar()
 * @method static cdlunique3river()
 * @method static cdlupsidegap2crows()
 * @method static cdlxsidegap3methods()
 * @method static ceil()
 * @method static cmo()
 * @method static correl()
 * @method static cos()
 * @method static cosh()
 * @method static dema()
 * @method static div()
 * @method static dx()
 * @method static ema()
 * @method static errno()
 * @method static exp()
 * @method static floor()
 * @method static get_compat()
 * @method static get_unstable_period()
 * @method static ht_dcperiod()
 * @method static ht_dcphase()
 * @method static ht_phasor()
 * @method static ht_sine()
 * @method static ht_trendline()
 * @method static ht_trendmode()
 * @method static kama()
 * @method static linearreg_angle()
 * @method static linearreg_intercept()
 * @method static linearreg_slope()
 * @method static linearreg()
 * @method static ln()
 * @method static log10()
 * @method static ma()
 * @method static macd()
 * @method static macdext()
 * @method static macdfix()
 * @method static mama()
 * @method static mavp()
 * @method static max()
 * @method static maxindex()
 * @method static medprice()
 * @method static mfi()
 * @method static midpoint()
 * @method static midprice()
 * @method static min()
 * @method static minindex()
 * @method static minmax()
 * @method static minmaxindex()
 * @method static minus_di()
 * @method static minus_dm()
 * @method static mom()
 * @method static mult()
 * @method static natr()
 * @method static obv()
 * @method static plus_di()
 * @method static plus_dm()
 * @method static ppo()
 * @method static roc()
 * @method static rocp()
 * @method static rocr100()
 * @method static rocr()
 * @method static rsi()
 * @method static sar()
 * @method static sarext()
 * @method static set_compat()
 * @method static set_unstable_period()
 * @method static sin()
 * @method static sinh()
 * @method static sma()
 * @method static sqrt()
 * @method static stddev()
 * @method static stoch()
 * @method static stochf()
 * @method static stochrsi()
 * @method static sub()
 * @method static sum()
 * @method static t3()
 * @method static tan()
 * @method static tanh()
 * @method static tema()
 * @method static trange()
 * @method static trima()
 * @method static trix()
 * @method static tsf()
 * @method static typprice()
 * @method static ultosc()
 * @method static var()
 * @method static wclprice()
 * @method static willr()
 * @method static wma()
 */
class Trader extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return TraderContract::class;
    }
}
